document: feedback-pipeline-workload
version: 1
data:
  name: cantata
  description: Fedora dog.unix.cantata.Cantata flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - cantata
