document: feedback-pipeline-workload
version: 1
data:
  name: fooyin
  description: Fedora org.fooyin.fooyin flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - fooyin
