document: feedback-pipeline-workload
version: 1
data:
  name: gpxsee
  description: Fedora org.gpxsee.GPXSee flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-kde6-app
  packages:
    - gpxsee
