document: feedback-pipeline-workload
version: 1
data:
  name: jumpnbump
  description: Fedora io.gitlab.LibreGames.jumpnbump flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-app
  packages:
    - jumpnbump
