document: feedback-pipeline-workload
version: 1
data:
  name: llvm21
  description: Fedora org.fedoraproject.Sdk.Extension.llvm21 flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-sdk
  packages:
    - clang21
    - clang21-analyzer
    - clang21-devel
    - clang21-libs
    - clang21-tools-extra
    - clang21-tools-extra-devel
    - compiler-rt21
    - git-clang-format21
    - libcxx
    - libcxx-devel
    - libcxxabi
    - libcxxabi-devel
    - libomp21
    - libomp21-devel
    - lld21
    - lld21-devel
    - lld21-libs
    - lldb21
    - lldb21-devel
    - llvm21
    - llvm21-cmake-utils
    - llvm21-devel
    - llvm21-googletest
    - llvm21-libs
    - llvm-libunwind
    - llvm-libunwind-devel
    - llvm21-test
    - python3-clang21
    - python3-lit
    - python3-lldb
    - llvm21-flatpak-config
    # for cleanup-commands (part of runtime)
    - coreutils-single
    - rpm
    - sed
