document: feedback-pipeline-workload
version: 1
data:
  name: nodejs22
  description: Fedora org.fedoraproject.Sdk.Extension.node22 flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-sdk
  packages:
    - nodejs22
    - nodejs22-bin
    - nodejs22-devel
    - nodejs22-npm
    - nodejs22-npm-bin
    - yarnpkg
    - nodejs22-flatpak-config
    # for cleanup-commands (part of runtime)
    - coreutils-single
