document: feedback-pipeline-workload
version: 1
data:
  name: texlive
  description: Fedora org.fedoraproject.Sdk.Extension.texlive flatpak
  maintainer: flatpak-sig
  labels:
    - flatpak-sdk
  packages:
    - texlive-*
    - asymptote
    - biber
    - ghostscript-tools-dvipdf
    - latexmk
    - psutils
    - t1utils
    - teckit
    - texlive-flatpak-config
    # for cleanup-commands (part of runtime)
    - coreutils-single
    - rpm
    - sed
